### ISSUE TITLE
ANF to CNF conversion

### ISSUE THREAD

**Issue by hadipourh** [meelgroup/bosphorus#11]
Dear developer team,

Is it possible to add an option to the tool, so that one can convert an ANF to it's CNF equivalent without creating the new variables? In the current version, when the ANF representation is converted to it's CNF equivalent, a lot of new variables are created, but in many cases we need to convert an ANF representation to the minimized (or approximately minimized) CNF representation without generating new variables. Thank you for creating such a useful tool. 

Kind regards, 
Hosein

**Comment by msoos** [comment]
Hi,

It's possible, however, unfortunately, that can easily lead to exponential CNF. This is a limitation of the CNF form, not of our tool. An XOR of length 100 will generate 2^99 clauses. That is not too far from the number of atoms in the universe. Are you sure you won't have such long XORs? If you only have short XORs then you can try to use the options:

(1)   `--cutnum 20` -- maximum 20 long plain XOR, this will still leave you half a million clauses for 20-long XORs

and

(2) `--karn 10` This will limit complicated polynomials to length 10 to be converted without extra variables.

However, we'd need to work more to make sure the above really doesn't add any variables, as Karnaugh-based conversion (`--karn 10`) is a heuristic that we'd need to force.

In general what you are asking rarely is practical due to the enormous size of the resulting CNF. Note that extra variables are not a problem in general for SAT solvers. Are you sure you don't have large polynomials? Because if you do, this solution is either very expensive or impossible.

**Comment by hadipourh** [comment]
Hello, 
Dear Mate, 
According to your nice explanation, I should change my strategy, and let the additional variables to be introduced. So, the simplified CNF form must be equisatisfiable with the original one. If they are equisatisfiable (and not equivalence) each satisfying assignment for the obtained CNF form, must satisfy the original one too, but the number of solutions might be increased when the additional variables are introduced. If I understand well, this conversion is not that useful in the cases where there must be a one-to-one relation between the solutions of simplified (CNF form), and the original one. For example in those cases we want to count the number of solutions for a given ANF, or CNF representation. Let me now if I am wrong please. I have also prepared the truth table of my Boolean function, readable vie espresso algorithm, and it's ANF here:
[tt_plus_anf.zip](https://github.com/meelgroup/bosphorus/files/4255300/tt_plus_anf.zip)


By the way: It would be better if you added an ability of converting a given truth table to the CNF , or ANF representation directly, because it is a common practical problem. For instance, in the symmetric-key cryptanalysis it is needed to convert the differential distribution of an Sbox to a CNF, modeling the differential behaviour of the given Sbox. For example take a look at the section 4.1 of the following paper please: 
[Comprehensive Security Analysis of CRAFT(https://tosc.iacr.org/index.php/ToSC/article/view/8466)

Thank you in advance for your time, and efforts,
Hosein

**Comment by msoos** [comment]
Hi,

Yes, indeed, you should ignore the number of variables. It has nothing to do with the complexity of the problem.

Re: Equisatisfiability. Sorry if we didn't clear this up, but the system is well-designed and it's meant to preserve the number of solutions. Exactly, and precisely :) If it did not, that would be a bug. Is there a bug you found? In case you did find such a bug, please make it minimal, give a full description of how to re-produce, what was the output, what was the expected output, and what you suspect may be going on.

Re:  "added an ability of converting a given truth table to the CNF , or ANF representation directly" unfortunately I don't understand what you mean here. Can you please give some examples? I had a look at Sect 4.1 but it doesn't talk about exact CNF/ANF representations and why you'd need them. The system doesn't need a specific ANF/CNF representation of a function to work. It may be slightly slower with a less optimized version, but there is almost never any need for exact ANF/CNF representation. But again, I may be misunderstanding this. Please give a few, but thorough, examples, including what you'd like the input to be, the output to be, and some reasons why you'd need this.

I hope the above helped,

Mate

**Comment by hadipourh** [comment]
Dear Mate,

Hope you are doing well. Regarding to the number of solutions. The attached file, contains the CNF of Skinny-128 Sbox in 'dimacs' format. The number of solutions for the given CNF must be 256, since it actually describe an 8-bit Sbox, and it's is known that the number of possible (input, output) for a given Sbox must be 256. You can reproduce this file via the following command in SageMath:
```
from sage.crypto.sbox import SBox
s = SBox([0x65 , 0x4c , 0x6a , 0x42 , 0x4b , 0x63 , 0x43 , 0x6b , 0x55 , 0x75 , 0x5a , 0x7a , 0x53 , 0x73 , 0x5b , 0x7b ,0x35 , 0x8c , 0x3a , 0x81 , 0x89 , 0x33 , 0x80 , 0x3b , 0x95 , 0x25 , 0x98 , 0x2a , 0x90 , 0x23 , 0x99 , 0x2b ,0xe5 , 0xcc , 0xe8 , 0xc1 , 0xc9 , 0xe0 , 0xc0 , 0xe9 , 0xd5 , 0xf5 , 0xd8 , 0xf8 , 0xd0 , 0xf0 , 0xd9 , 0xf9 ,0xa5 , 0x1c , 0xa8 , 0x12 , 0x1b , 0xa0 , 0x13 , 0xa9 , 0x05 , 0xb5 , 0x0a , 0xb8 , 0x03 , 0xb0 , 0x0b , 0xb9 ,0x32 , 0x88 , 0x3c , 0x85 , 0x8d , 0x34 , 0x84 , 0x3d , 0x91 , 0x22 , 0x9c , 0x2c , 0x94 , 0x24 , 0x9d , 0x2d ,0x62 , 0x4a , 0x6c , 0x45 , 0x4d , 0x64 , 0x44 , 0x6d , 0x52 , 0x72 , 0x5c , 0x7c , 0x54 , 0x74 , 0x5d , 0x7d ,0xa1 , 0x1a , 0xac , 0x15 , 0x1d , 0xa4 , 0x14 , 0xad , 0x02 , 0xb1 , 0x0c , 0xbc , 0x04 , 0xb4 , 0x0d , 0xbd ,0xe1 , 0xc8 , 0xec , 0xc5 , 0xcd , 0xe4 , 0xc4 , 0xed , 0xd1 , 0xf1 , 0xdc , 0xfc , 0xd4 , 0xf4 , 0xdd , 0xfd ,0x36 , 0x8e , 0x38 , 0x82 , 0x8b , 0x30 , 0x83 , 0x39 , 0x96 , 0x26 , 0x9a , 0x28 , 0x93 , 0x20 , 0x9b , 0x29 ,0x66 , 0x4e , 0x68 , 0x41 , 0x49 , 0x60 , 0x40 , 0x69 , 0x56 , 0x76 , 0x58 , 0x78 , 0x50 , 0x70 , 0x59 , 0x79 ,0xa6 , 0x1e , 0xaa , 0x11 , 0x19 , 0xa3 , 0x10 , 0xab , 0x06 , 0xb6 , 0x08 , 0xba , 0x00 , 0xb3 , 0x09 , 0xbb ,0xe6 , 0xce , 0xea , 0xc2 , 0xcb , 0xe3 , 0xc3 , 0xeb , 0xd6 , 0xf6 , 0xda , 0xfa , 0xd3 , 0xf3 , 0xdb , 0xfb ,0x31 , 0x8a , 0x3e , 0x86 , 0x8f , 0x37 , 0x87 , 0x3f , 0x92 , 0x21 , 0x9e , 0x2e , 0x97 , 0x27 , 0x9f , 0x2f ,0x61 , 0x48 , 0x6e , 0x46 , 0x4f , 0x67 , 0x47 , 0x6f , 0x51 , 0x71 , 0x5e , 0x7e , 0x57 , 0x77 , 0x5f , 0x7f ,0xa2 , 0x18 , 0xae , 0x16 , 0x1f , 0xa7 , 0x17 , 0xaf , 0x01 , 0xb2 , 0x0e , 0xbe , 0x07 , 0xb7 , 0x0f , 0xbf ,0xe2 , 0xca , 0xee , 0xc6 , 0xcf , 0xe7 , 0xc7 , 0xef , 0xd2 , 0xf2 , 0xde , 0xfe , 0xd7 , 0xf7 , 0xdf , 0xff])
print(s.cnf(format = 'dimacs'))
```
CNF file: [skinny64_sbox.zip](https://github.com/meelgroup/bosphorus/files/4282991/skinny64_sbox.zip)
I solved the above SAT problem via your nice tool, called CryptoMiniSat5 with the following command: 
```
cryptominisat5 --verb 0 --maxsol 500 skinny64_sbox.cnf > solutions.txt
```
As you can see in the attached file [solutions.zip](https://github.com/meelgroup/bosphorus/files/4282923/solutions.zip), there are only 256 different solutions for this SAT problem. Let's simplify this CNF with the Bosphorus, to see whether it keeps the number of solutions unchanged or not. 
I simplified it via the following command: 
```
./bosphorus --cnfread skinny64_sbox.cnf --cnfwrite simplified.cnf
```
The simplified version of the above SAT problem, has been included in the [simplified.zip](https://github.com/meelgroup/bosphorus/files/4282934/simplified.zip). When I solved the simplified.cnf with the CryptoMiniSat5, I observed that it has more than 256 solutions. I solved it via the following command: 
```
cryptominisat5 --verb 0 --maxsol 500 simplified.cnf > solutions1.txt
```
As you can see in [solutions1.txt](https://github.com/meelgroup/bosphorus/files/4282968/solutions1.txt) file, there are more than 256 different solutions for the simplified CNF! So, I think the Bosphorus doesn't reserve the equality. **Let me know if I am wrong please**. 

Regarding to the conversion of a truth table to the CNF or ANF representation, I mean it would be better if one could give the truth table to the Bosphorus, and get it's CNF, or ANF representation. Let me know if it is still not clear enough. Thank you for your time, and efforts for creating a lot of useful SAT tools.

Kind regards, 
Hosein

**Comment by msoos** [comment]
Aaaaah. Sorry. The CNF reader is a _very_ experimental system. Sorry about that, it's not clear :( I want to remove the CNF reader but maybe I'll just fix it up. I will do it soon, though, and this issue will not be closed until I fix it.

My advice is that you should output that S box as ANF though. It's a LOT better that way! If you output it as ANF then you can use Bosphorus to read it `--anfread FILE` and generate a simplified CNF. Bosphorus is a *lot* better at taking ANF and producing a CNF. It wasn't really meant to be as a CNF simplifier. Sorry for the confusion this caused :(

The good new is, if you output that ANF as ANF and use Bosphorus on the ANF to generate a CNF, it should be giving you a lot more optimal CNF than Sage :) I believe this set of commands does what you want:

```
from sage.crypto.sbox import SBox
s = SBox([0x65 , 0x4c , 0x6a , 0x42 , 0x4b , 0x63 , 0x43 , 0x6b , 0x55 , 0x75 , 0x5a , 0x7a , 0x53 , 0x73 , 0x5b , 0x7b ,0x35 , 0x8c , 0x3a , 0x81 , 0x89 , 0x33 , 0x80 , 0x3b , 0x95 , 0x25 , 0x98 , 0x2a , 0x90 , 0x23 , 0x99 , 0x2b ,0xe5 , 0xcc , 0xe8 , 0xc1 , 0xc9 , 0xe0 , 0xc0 , 0xe9 , 0xd5 , 0xf5 , 0xd8 , 0xf8 , 0xd0 , 0xf0 , 0xd9 , 0xf9 ,0xa5 , 0x1c , 0xa8 , 0x12 , 0x1b , 0xa0 , 0x13 , 0xa9 , 0x05 , 0xb5 , 0x0a , 0xb8 , 0x03 , 0xb0 , 0x0b , 0xb9 ,0x32 , 0x88 , 0x3c , 0x85 , 0x8d , 0x34 , 0x84 , 0x3d , 0x91 , 0x22 , 0x9c , 0x2c , 0x94 , 0x24 , 0x9d , 0x2d ,0x62 , 0x4a , 0x6c , 0x45 , 0x4d , 0x64 , 0x44 , 0x6d , 0x52 , 0x72 , 0x5c , 0x7c , 0x54 , 0x74 , 0x5d , 0x7d ,0xa1 , 0x1a , 0xac , 0x15 , 0x1d , 0xa4 , 0x14 , 0xad , 0x02 , 0xb1 , 0x0c , 0xbc , 0x04 , 0xb4 , 0x0d , 0xbd ,0xe1 , 0xc8 , 0xec , 0xc5 , 0xcd , 0xe4 , 0xc4 , 0xed , 0xd1 , 0xf1 , 0xdc , 0xfc , 0xd4 , 0xf4 , 0xdd , 0xfd ,0x36 , 0x8e , 0x38 , 0x82 , 0x8b , 0x30 , 0x83 , 0x39 , 0x96 , 0x26 , 0x9a , 0x28 , 0x93 , 0x20 , 0x9b , 0x29 ,0x66 , 0x4e , 0x68 , 0x41 , 0x49 , 0x60 , 0x40 , 0x69 , 0x56 , 0x76 , 0x58 , 0x78 , 0x50 , 0x70 , 0x59 , 0x79 ,0xa6 , 0x1e , 0xaa , 0x11 , 0x19 , 0xa3 , 0x10 , 0xab , 0x06 , 0xb6 , 0x08 , 0xba , 0x00 , 0xb3 , 0x09 , 0xbb ,0xe6 , 0xce , 0xea , 0xc2 , 0xcb , 0xe3 , 0xc3 , 0xeb , 0xd6 , 0xf6 , 0xda , 0xfa , 0xd3 , 0xf3 , 0xdb , 0xfb ,0x31 , 0x8a , 0x3e , 0x86 , 0x8f , 0x37 , 0x87 , 0x3f , 0x92 , 0x21 , 0x9e , 0x2e , 0x97 , 0x27 , 0x9f , 0x2f ,0x61 , 0x48 , 0x6e , 0x46 , 0x4f , 0x67 , 0x47 , 0x6f , 0x51 , 0x71 , 0x5e , 0x7e , 0x57 , 0x77 , 0x5f , 0x7f ,0xa2 , 0x18 , 0xae , 0x16 , 0x1f , 0xa7 , 0x17 , 0xaf , 0x01 , 0xb2 , 0x0e , 0xbe , 0x07 , 0xb7 , 0x0f , 0xbf ,0xe2 , 0xca , 0xee , 0xc6 , 0xcf , 0xe7 , 0xc7 , 0xef , 0xd2 , 0xf2 , 0xde , 0xfe , 0xd7 , 0xf7 , 0xdf , 0xff])
f = s.component_function(1)
print(f.algebraic_normal_form())
```

This will give you the polynomial:

```
x0*x1*x2*x3*x4 + x0*x1*x2*x3*x5 + x0*x1*x2*x3*x6*x7 + x0*x1*x2*x3*x6 + x0*x1*x2*x3*x7 + x0*x1*x2*x3 + x0*x1*x2*x5 + x0*x1*x2 + x0*x1*x3*x4 + x0*x1*x3*x5 + x0*x1*x3*x6*x7 + x0*x1*x3*x6 + x0*x1*x3*x7 + x0*x1*x3 + x0*x1*x4*x6 + x0*x1*x4 + x0*x1*x5 + x0*x1*x6*x7 + x0*x1*x7 + x0*x1 + x0*x2*x3*x4 + x0*x2*x3*x5 + x0*x2*x3*x6*x7 + x0*x2*x3*x6 + x0*x2*x3*x7 + x0*x2*x3 + x0*x2*x5 + x0*x2 + x0*x3*x4*x6 + x0*x3*x5*x6 + x0*x3*x7 + x0*x3 + x0*x5*x6 + x0*x6 + x0*x7 + x0 + x1*x2*x3*x4*x6 + x1*x2*x3*x6 + x1*x2*x4*x6 + x1*x2*x4 + x1*x2*x5 + x1*x2*x6*x7 + x1*x2*x7 + x1*x2 + x1*x3*x4*x6 + x1*x3*x6 + x1*x5*x6 + x1*x6 + x1*x7 + x1 + x2*x3*x4 + x2*x3*x5*x6 + x2*x3*x5 + x2*x3*x6*x7 + x2*x5*x6 + x2*x6 + x2*x7 + x3*x4*x6 + x3*x6 + x5*x6 + x6 + x7 + 1
```

This is the polynomial for the S-box. So let's set a new variable, `x8` that will be the output of the S-box given `x0...x7`. To do this, just put `+x8` at the end of that polynomial: 

```
x0*x1*x2*x3*x4 + x0*x1*x2*x3*x5 + x0*x1*x2*x3*x6*x7 + x0*x1*x2*x3*x6 + x0*x1*x2*x3*x7 + x0*x1*x2*x3 + x0*x1*x2*x5 + x0*x1*x2 + x0*x1*x3*x4 + x0*x1*x3*x5 + x0*x1*x3*x6*x7 + x0*x1*x3*x6 + x0*x1*x3*x7 + x0*x1*x3 + x0*x1*x4*x6 + x0*x1*x4 + x0*x1*x5 + x0*x1*x6*x7 + x0*x1*x7 + x0*x1 + x0*x2*x3*x4 + x0*x2*x3*x5 + x0*x2*x3*x6*x7 + x0*x2*x3*x6 + x0*x2*x3*x7 + x0*x2*x3 + x0*x2*x5 + x0*x2 + x0*x3*x4*x6 + x0*x3*x5*x6 + x0*x3*x7 + x0*x3 + x0*x5*x6 + x0*x6 + x0*x7 + x0 + x1*x2*x3*x4*x6 + x1*x2*x3*x6 + x1*x2*x4*x6 + x1*x2*x4 + x1*x2*x5 + x1*x2*x6*x7 + x1*x2*x7 + x1*x2 + x1*x3*x4*x6 + x1*x3*x6 + x1*x5*x6 + x1*x6 + x1*x7 + x1 + x2*x3*x4 + x2*x3*x5*x6 + x2*x3*x5 + x2*x3*x6*x7 + x2*x5*x6 + x2*x6 + x2*x7 + x3*x4*x6 + x3*x6 + x5*x6 + x6 + x7 + 1 + x8
```

Now, if you want the S-box output to be `0` you add a line to your ANF:

```
x8
```

and if you want the S-box output to be `1`, you  add this line:

```
x8 + 1
```

Of course *without* setting the S-box to any value, you should have 256 solutions. Indeed:
```
$ ./bosphorus --anfread sbox.anf --cnfwrite sbox.cnf

$ /home/soos/development/sat_solvers/cryptominisat/build/cryptominisat5 sbox.cnf  --maxsol 500
[...]
c Number of solutions found until now:    256
s UNSATISFIABLE
```

If you add `x8` then you have 128:
```
$ /home/soos/development/sat_solvers/cryptominisat/build/cryptominisat5 sbox.cnf  --maxsol 500
[...]
c Number of solutions found until now:    128
s UNSATISFIABLE
```

and if you add `x8+1`
```
$ /home/soos/development/sat_solvers/cryptominisat/build/cryptominisat5 sbox.cnf  --maxsol 500
[...]
c Number of solutions found until now:    128
s UNSATISFIABLE
```

So the S-box is balanced.

I *strongly* suggest using the ANF format from Sage. It's the right thing to do :)

**Comment by msoos** [comment]
As a last comment, if you give the option `--karn 9` to Bosphorus you will see that the CNF is *significantly* smaller than what Sage produces. In fact, it's so much smaller that your speed will be a *lot* faster on solving problems that have this S-box inside of them.

**Comment by msoos** [comment]
I am closing, as I believe the above answered the question and approx 24h has went by. Please let us know if the above didn't solve the issue :) Good luck with your project,

Mate

**Comment by hadipourh** [comment]
Dear Mate,

Thanks a lot for your explanations. Yes, your answer was clear enough. I also compared the CNFs generated by your tool, and SageMath, and as you already mentioned, Bosphorus generates a lighter CNF for a given Sbox. 

Kind regards, 
Hosein

**Comment by msoos** [comment]
Glad it all worked out in the end! Good luck,

Mate

**Comment by msoos** [comment]
Hey,

I have now a new version of the tool, and it incorporates the solution counting and printing to the tool itself! I think you might find this useful. To use it:

```
docker run --rm -v `pwd`/:/dat/ msoos/bosphorus \
    --anfread /dat/myfile.anf \
    --cnfwrite /dat/myfile.cnf \
    --solve --allsol
[...]
s ANF-SATISFIABLE
v x(0) x(1) x(2) x(3)
s ANF-SATISFIABLE
v x(0) x(1) 1+x(2) 1+x(3)
s ANF-UNSATISFIABLE
c Number of solutions found: 2
```
Cheers,

Mate

PS: I am planning to fix up the CNF system next. It shouldn't be too difficult. I now have a fuzzer so I can find out issues like the above where the number of solutions changed.
