### ISSUE TITLE
README -s mistake?

### ISSUE THREAD

**Issue by mfernan2** [meelgroup/bosphorus#14]
The README lists the following example command:

```
$ ./bosphorus --anfread test.anf --anfwrite out.anf --cnfwrite out.cnf -s --solvewrite solution
```

However running this with Bosphorus 3.0 produces:

```
Some option you gave was wrong. Please give '--help' to get help
Unkown option: unrecognised option '-s'
```

Running without `-s` produces no solution file. I think the intended option here is `--solve`.

**Comment by msoos** [comment]
Ah, great catch, thank you so much! Fixed, with attribution :)

**Comment by mfernan2** [comment]
Thanks! Though shouldn't 4ce8b48fd459978b64f5dc9347a07a94062742a7 have changed `-s` to `--solve`? Otherwise, in my testing, the solution file did not get written so the later README steps don't work.

**Comment by msoos** [comment]
Ah, good point, now fixed that too! Good catch! Sorry, I "tested" it, but forgot to delete the file, so I didn't detect that it wasn't in fact written. Sorry :S I need write some test cases. Fixed for now :)
