### ISSUE TITLE
Evaluating the key research space

### ISSUE THREAD

**Issue by GoldenHamed** [meelgroup/bosphorus#19]
Hello,
how to modify the source code such that enable it to support counting and outputting all the
possible key solutions automatically?

**Comment by msoos** [comment]
Hi,

You can translate your ANF to a CNF, and then use a SAT solver like CryptoMiniSat with the option `--maxsol 1000000` to output all solutions. You can then use the `map_solution.py` script to map back all solutions.

I hope this helped,

Mate

**Comment by GoldenHamed** [comment]
Thank you very much.

**Comment by GoldenHamed** [comment]
> Hi,
> 
> You can translate your ANF to a CNF, and then use a SAT solver like CryptoMiniSat with the option `--maxsol 1000000` to output all solutions. You can then use the `map_solution.py` script to map back all solutions.
> 
> I hope this helped,
> 
> Mate

Hi, thank you very much for your response.
What is the input format  of the map file?

**Comment by msoos** [comment]
The map file is emitted by the system. Please check the `--help`.

**Comment by GoldenHamed** [comment]
> The map file is emitted by the system. Please check the `--help`.

Thank you, 
The output is as follows:
v x(0) 1+x(1) x(2) x(3) x(4) 1+x(5) x(6) x(7) x(8) x(9) x(10) x(11) x(12) 1+x(13) x(14)
Outputs that are just variable names have a value of zero?

**Comment by msoos** [comment]
I have now added an explanation here in the README, check it out!

https://github.com/meelgroup/bosphorus/blob/master/README.md#mapping-solutions-from-cnf-to-anf

**Comment by GoldenHamed** [comment]
> I have now added an explanation here in the README, check it out!
> 
> https://github.com/meelgroup/bosphorus/blob/master/README.md#mapping-solutions-from-cnf-to-anf

Thank you very much.
