### ISSUE TITLE
Bug in `subsitute` function?

### ISSUE THREAD

**Issue by ErwinHaasnoot** [meelgroup/bosphorus#24]
Dear Mate,

I think I have uncovered a bug in a critical function that is called during the ElimLin simplification process. The specific line is this:

https://github.com/meelgroup/bosphorus/blob/eaed7eac38f319728721136b5597b160228f6a8c/src/anfutils.cpp#L120

If we consider the very simple case where:

from_var = x(1)
poly = x(2)
to_poly = <don't care>

The polynomial quotient will be 0 (and the remainder x(2) )

The line in question will cause the function to return the value of the quotient * to_poly, which will also always be 0. We would instead expect the output to be unchanged (considering x(1) is not present in the `poly`). 

In the case where from_var == poly, the quotient will be `1` and thus should be covered by the next branch in the if-else statement.

In practice, I don't know how often a simplification where the `poly` is a singleton happens, but I thought it would be good for you to have another look at it, so that consistency of the simplification process can be guaranteed.

Btw: in _large_ polynomials, this function is a significant bottleneck with exponential time-complexity. I am working on a pull request with an algorithm that is more suited to the CUDD back-end that BRiAl uses. I hope you will consider it by the time the request is made!

Best,

Erwin

**Comment by msoos** [comment]
Hi Erwin,

Oh wow, thank you so much for spotting this one! Great catch! Is there a quick fix to the code that you think could work? I'm knee deep in some other research code right now, and since you are so deep into CUDD and have looked at this recently, perhaps you can propose a quick fix? If you can propose a quick fix, that'd be so cool! Also, you working on a CUDD version that's _much_ faster sounds amazing!

By the way, since you are so deep into this :) Do you have some cool ideas/thoughts about what you think could be improved/fixed/updated in our system? Do you like the system in general? I/we were hoping that this could become a system used more widely, and I'm seeing quite a bit of uptick in use (which is great!) but perhaps you have some cool ideas we could help integrate so it'd be even more usable?

Thanks again for the great bug report, and looking forward to your thoughts,

Mate

**Comment by ErwinHaasnoot** [comment]
Hi Mate!

Thanks for your enthusiastic response! 

Regarding the quick fix, the comments around the seg faults scared me a bit, see e.g.

https://github.com/meelgroup/bosphorus/blob/eaed7eac38f319728721136b5597b160228f6a8c/src/anfutils.cpp#L119

but if I can disregard that, I would suggest there are three cases that matter, and all are related to the value of the quotient, which can be 0, 1, or something more complex. The part that handles the complex quotients also _should_ work for the cases where the quotient is 0 or 1, it only does a lot of unnecessary work.

Anyway, I would suggest the following code as the body of the `subsitute` function:

```
BoolePolynomial quotient = poly / from_var;

if( quotient.isZero() ) { // 
    // `from_var` does not occur in `poly`, so just keep `poly` as it is.
    return;
} else if (quotient.isOne()) { // just
    // from_var == poly, so return the value of to_poly.
    quotient *= to_poly;
    swap(quotient, poly); // because we are returning poly
} else {
    // build up the return value based on the quotient and the remainder
    quotient *= to_poly;
    for (const BooleMonomial& mono : poly) {
        if (!mono.reducibleBy(from_var)) {
            quotient += mono;
        }
    }
    swap(quotient, poly); // because we are returning poly
}
```

We are having some difficulties with the function that is intended to replace it. In most simple cases it returns the same result, but when the polynomials become more complex, it seems we are not correctly taking variable ordering into account. 

The testing is a bit frustrating at this moment. We only have some very large ANF's currently that show the problem. ANFs on which it takes a couple of hours to complete a single ElimLin round (whereas our algo completes in a few hundred milliseconds, albeit with the wrong answer). We want to find simpler ANFs that show the problem, but the long time it takes to test said ANFs makes this process a bit frustrating. If you have some time, maybe we could look into this problem together?

I would be happy to share some further thoughts on Bosphorus as well! I'll try and find the time for it in the weekend :)

Best,

Erwin

**Comment by ErwinHaasnoot** [comment]
I have made a pull request for the bugfix! Gotta have that contributor status on github ;)

**Comment by msoos** [comment]
Ah, nice, finally completely fixed :) Thank you @aljungberg !

**Comment by ErwinHaasnoot** [comment]
Interesting, that seems to slipped my (limited) testing. As I understand
you have now taken some steps to introduce fuzz-testing and unit-testing to
the project. Awesome 😁

Have you been able to look at my other thoughts on the subject of CUDD and
Bosphorus? Would be happy converse on that further!

**Comment by msoos** [comment]
Ah, yes, your thoughts! I am sorry. Let me get back to them tomorrow. I really enjoyed what you wrote and I just felt overwhelmed by so many things. Sorry. I will read through them in detail tomorrow and get back to you. To be honest, I would enjoy having a chat with you as well, perhaps in an in-person meeting, we could discuss easier? What do you think? I'll read your thoughts in detail first, of course. If you think meeting is a good idea, drop me a mail at soos.mate@gmail.com!

**Comment by ErwinHaasnoot** [comment]
Me too! Ill send you a message soon. Currently on a holiday for another
week 😁
