### ISSUE TITLE
different CNF 

### ISSUE THREAD

**Issue by bobcrypt** [meelgroup/bosphorus#3]
Hi!
I have been using both bosphorus and anf2cnf.py. For some fixed system of ANF equations, even by changing the cut parameter, I have been unable to generate by bosphorus the same CNF that I obtain by anf2cnf.py. Is it possible to do this in some way? I'm very interested to the CNF obtained by anf2cnf.py because I have found that, for my problem, this is more efficient than the ones that I'm be able to obtain by bosphorus. But I need bosphorus to convert back solutions to the ANF form.
Many thanks in advance. Bob

**Comment by msoos** [comment]
Hi,

Hmm... Bosphorus is supposed to be significantly better. It can not only convert much better, but also simplify using various methods. How big are the differences? Also, have you tried turning off the "karnaugh"-based ANF translation in Bosphorus? Please just give "  --karn 0". Please let us know if this helped! Thanks,

Mate

**Comment by msoos** [comment]
I am closing as there was no response for many months.
