### ISSUE TITLE
It can't convert ANF to CNF.

### ISSUE THREAD

**Issue by zfx-code** [meelgroup/bosphorus#37]
Hello, I use bosphorus to convert ANF to CNF.
The command is "./bosphorus --anfread fail_create_cnf.eqs --cnfwrite fail_create_cnf.cnf "
But it kept stopping at the first Iteration 0, I don't know what's wrong.
The attach is my fail ANF file "fail_create_cnf.zip".
Thank you!
![image](https://user-images.githubusercontent.com/65902313/186926151-0fd302b5-df90-408e-9813-fa2d21430e2d.png)

[fail_create_cnf.zip](https://github.com/meelgroup/bosphorus/files/9433980/fail_create_cnf.zip)

**Comment by zfx-code** [comment]
Sorry, maybe it's because the ANF is a bit complex, I should have waited a little longer.

**Comment by msoos** [comment]
Glad it worked!

Mate
