### ISSUE TITLE
Current master branch does not properly NULL terminate arguments to execl

### ISSUE THREAD

**Issue by avinashvarna** [meelgroup/bosphorus#8]
First of all, many thanks for making this tool freely available! 

It appears that a recent commit (https://github.com/meelgroup/bosphorus/commit/dabd13ac750a3dcacb76b2ce45b0884fec8c0ef4) removed the last argument to execl in satsolve.cpp which needs to be NULL:
https://github.com/meelgroup/bosphorus/blob/5a3e24f79a3acf70eae2546d76ed2e1c46e7f271/src/satsolve.cpp#L73

Coupled with the redirection of stdout and stderr to the pipe, this leads to an error of the form 
```
ERROR! Line 'ERROR! Could not execute '/usr/local/bin/cryptominisat5'' doesn't contain correct starting character
```
which is not easily interpreted as being a problem with running the child process (at least, it wasn't obvious to me).

To reproduce, build from master branch and run the example in README

My suggestion is that it may be better to not redirect stderr to the pipe, which would allow the error to be printed at the right place. 

I will shortly submit a PR that makes both these changes. Please merge if appropriate.

Thanks
Avinash

**Comment by msoos** [comment]
Oh, well-spotted, thanks! Merged :) Let us know if the tool was useful,

Mate

**Comment by avinashvarna** [comment]
Thanks! The tool has been very useful on some of the problems I've been working on and has produced good results (Unfortunately, I cannot get into the details at this time).

I have another enhancement that I want to suggest, and I will submit a separate PR for it.

**Comment by msoos** [comment]
Great to hear! Responded to your other PR :) Thanks again!
